import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import type { AppProps } from "next/app";
import dynamic from "next/dynamic";
import Head from "next/head";
import "reset-css";

import "@fontsource/lato/300.css";
import "@fontsource/lato/400.css";
import "@fontsource/lato/700.css";
import "@fontsource/lato/900.css";

import ".././styles/globals.css";
import Layout from "../components/Layout";

import {theme} from "../theme";
import { Suspense } from "react";

// const PwaUpdater = dynamic(() => import("../utils/PwaUpdater"), { ssr: false });

export default function App({ Component, pageProps }: AppProps) {
    return (
        <ChakraProvider theme={theme} cssVarsRoot="body">
            {/* <PwaUpdater msg="we want to send you notification" />        */}
            <Head>
                <title>ta&apos;am - server better</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Layout>
                    <Suspense fallback="loading....">
                        <Component {...pageProps} />
                    </Suspense>
                </Layout>
            </main>
        </ChakraProvider>
    );
}
