import Head from "next/head";
import {  Heading, Box, Container, CardBody, Icon } from "@chakra-ui/react";
import Layout from "../components/Layout";

import "@fontsource/lato/300.css";
import "@fontsource/lato/400.css";
import "@fontsource/lato/700.css";
import "@fontsource/lato/900.css";
import CardContainer from "../components/Card";
import { MdDashboardCustomize } from "react-icons/md";
import HomeView from "../components/Home";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {/* top container */}
                <Layout>
                        <HomeView />
                </Layout>
            </main>
        </>
    );
}
