import Head from "next/head";
import { Text, Heading, Box, Container } from "@chakra-ui/react";
import Layout from "../components/Layout";

import "@fontsource/lato/300.css";
import "@fontsource/lato/400.css";
import "@fontsource/lato/700.css";
import "@fontsource/lato/900.css";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {/* top container */}
                <Layout>
                    <Box minWidth="450px" shadow="innerShadow" minHeight="100vh">
                        <Container
                            display="flex"
                            width="full"
                            height="270px"
                            bg="white"
                        ></Container>
                    </Box>
                </Layout>
            </main>
        </>
    );
}
